import openai
openai.api_key = 'your-openai-key'

def generate_recommendation(sensor_type, value):
    prompt = f"Sensor: {sensor_type}\nObserved value: {value}\nWhat could be the issue and recommended action?"

    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=100
    )

    return response.choices[0].text.strip()

# This function generates a recommendation based on the sensor type and observed value.
# It uses OpenAI's GPT-3 model to generate a text response.
# The function takes two parameters: sensor_type (a string representing the type of sensor)
# and value (a float representing the observed value).
# It returns a string containing the recommendation generated by the model.